### PR TITLE
Scheduled reminders with participant custom fields

### PR DESCRIPTION
**Pull request by johanv**
This makes participant fields (including custom fields) work for scheduled reminders.

I created lots of interfaces, in an attempt to create readable code. Which kinda failed because I couldn't get PSR-4 namespaces working :-).

But hey, it seems to work in it's basic form. You can use tokens à la {participant.custom_4}. But it can still use some finetuning (role names instead of role id's, proper date formatting, and things like that.)

### CODE REVIEW

**Comment by magnolia61** [comment]
Hi Johan, great to see this addition! Unfortunately I can;t get it to work yet.
I'm using CiviCRM 5.5.2 with Drupal 7.5.9. With no other extensions that impact tokens.
Using the syntax: `{participant.custom_900}`. What can I do to help you with test & debug?

**Comment by magnolia61** [comment]
Update: I got the participant tokens working. The email template I used failed because it also listed some event custom tokens (syntax: {event.custom_658}) I think that is a whole different topic, right?
Anyway, I can conform participant tokens work in the scheduled reminders with this PR using this extension. Thanks!

**Comment by johanv** [comment]
@magnolia61 It doesn't work with event tokens yet, but it is not hard to fix that. I will try adding it next week; I have a busy weekend.

**Comment by johanv** [comment]
@magnolia61 There is something strange going on with the event custom fields. They seem to be supported out of the box in CiviCRM: if you create a scheduled reminder with only event tokens (including tokens for custom fields), it works. If you add tokens for other entities, the event custom fields don't work.

**Comment by johanv** [comment]
Ignore what I said. Event tokens work out of the box, even without extension. Just make sure you use the correct ID in your token {event.custom_ID}. 🤦

**Pull request merged**
